[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc", "rustc", "cargo", "pkg-config"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv", 
    ". /opt/venv/bin/activate && pip install --upgrade pip wheel setuptools",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "python webhook_server.py" 