[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app.py" aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app.py"
